# Generated by Django 3.1.3 on 2023-02-24 20:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='caducidad',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 24, 14, 5, 53, 655685)),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='description',
            field=models.TextField(blank=True, default='Licor'),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='destilado',
            field=models.CharField(blank=True, default='alcohol', max_length=50),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='edicion',
            field=models.CharField(blank=True, default='Standar', max_length=50),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='nombre',
            field=models.CharField(blank=True, default='???', max_length=50),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='size',
            field=models.CharField(blank=True, default='1L', max_length=50),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='tipo_envase',
            field=models.CharField(blank=True, default='Botella de cristal', max_length=50),
        ),
    ]
