# Generated by Django 3.1.3 on 2023-04-13 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='caducidad',
            field=models.DateField(default=datetime.datetime(2023, 7, 13, 8, 34, 49, 978843)),
        ),
    ]
