# Generated by Django 3.1.3 on 2023-02-24 20:08

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0002_auto_20230224_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='caducidad',
            field=models.DateField(default=datetime.datetime(2023, 5, 24, 14, 8, 48, 917602)),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='edicion',
            field=models.CharField(default='Standar', max_length=50),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
