# Generated by Django 3.1.3 on 2023-02-24 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0003_auto_20230224_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquor',
            name='pais_origen',
            field=models.CharField(blank=True, default='Mexico', max_length=50),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='caducidad',
            field=models.DateField(default=datetime.datetime(2023, 5, 24, 14, 17, 31, 63102)),
        ),
    ]
